### ISSUE TITLE
No tasks found from Nuget package

### ISSUE THREAD

**Issue by Svenskapojkarna** [CommunityHiQ/Frends.Community.Multipart.SendMultipartRequest#2]
When you try to import the task to Frends from task feed, Frends will say that there are no tasks in the package.
![image](https://user-images.githubusercontent.com/36008914/169755804-2b4f039d-7b27-4c4b-9705-9d8d2d10e7c3.png)

**Comment by RikuVirtanen** [comment]
Issue was fixed with newer Frends but when testing to import to a Frends version 5.2 or 5.3 the same error is thrown.

**Comment by Svenskapojkarna** [comment]
Probably because the task is targeting only .NET6.

**Comment by RikuVirtanen** [comment]
Fixed in PR #5
